-- LOOMORA ERP - PostgreSQL DDL Schema
-- Handloom & Textile Management Platform

CREATE TABLE IF NOT EXISTS roles (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    code VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255),
    is_system BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS role_permissions (
    id VARCHAR(36) PRIMARY KEY,
    role_id VARCHAR(36) REFERENCES roles(id) ON DELETE CASCADE NOT NULL,
    module VARCHAR(50) NOT NULL,
    can_view BOOLEAN DEFAULT FALSE NOT NULL,
    can_create BOOLEAN DEFAULT FALSE NOT NULL,
    can_edit BOOLEAN DEFAULT FALSE NOT NULL,
    can_delete BOOLEAN DEFAULT FALSE NOT NULL,
    can_approve BOOLEAN DEFAULT FALSE NOT NULL,
    can_export BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS plants (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    location VARCHAR(200) NOT NULL,
    manager_name VARCHAR(100),
    contact_phone VARCHAR(50),
    email VARCHAR(100),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS departments (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(255),
    department_head VARCHAR(100),
    plant_id VARCHAR(36) REFERENCES plants(id) ON DELETE SET NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY,
    employee_id VARCHAR(50) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    phone VARCHAR(50),
    password_hash VARCHAR(255) NOT NULL,
    department_id VARCHAR(36) REFERENCES departments(id) ON DELETE SET NULL,
    role_id VARCHAR(36) REFERENCES roles(id) ON DELETE RESTRICT NOT NULL,
    designation VARCHAR(100),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    avatar_url VARCHAR(500),
    last_login TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS user_plants (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    plant_id VARCHAR(36) REFERENCES plants(id) ON DELETE CASCADE NOT NULL,
    is_primary BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    user_name VARCHAR(150) NOT NULL,
    module VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    record_id VARCHAR(50),
    record_title VARCHAR(200),
    description TEXT NOT NULL,
    ip_address VARCHAR(50) DEFAULT '127.0.0.1',
    status VARCHAR(20) DEFAULT 'SUCCESS' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS login_activity (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL,
    email VARCHAR(150) NOT NULL,
    ip_address VARCHAR(50) DEFAULT '127.0.0.1' NOT NULL,
    device VARCHAR(100) DEFAULT 'Desktop' NOT NULL,
    browser VARCHAR(100) DEFAULT 'Chrome' NOT NULL,
    status VARCHAR(20) DEFAULT 'SUCCESS' NOT NULL,
    failure_reason VARCHAR(255),
    login_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    logout_time TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS user_approvals (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    requested_role_id VARCHAR(36) REFERENCES roles(id) ON DELETE SET NULL,
    requested_plant_id VARCHAR(36) REFERENCES plants(id) ON DELETE SET NULL,
    requested_by VARCHAR(150) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    decision_notes TEXT,
    decided_by VARCHAR(150),
    decided_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Master Data Tables
CREATE TABLE IF NOT EXISTS uom (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS tax_rates (
    id VARCHAR(36) PRIMARY KEY,
    tax_code VARCHAR(50) UNIQUE NOT NULL,
    tax_name VARCHAR(100) NOT NULL,
    gst_percentage DOUBLE PRECISION NOT NULL,
    hsn_code VARCHAR(50) NOT NULL,
    tax_category VARCHAR(100),
    effective_from VARCHAR(50),
    effective_to VARCHAR(50),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS colours (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    colour_family VARCHAR(100),
    hex_code VARCHAR(10) NOT NULL,
    dye_type VARCHAR(100),
    description VARCHAR(255),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS designs (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    pattern_type VARCHAR(100),
    motif VARCHAR(150),
    collection VARCHAR(150),
    description TEXT,
    reference_image_url VARCHAR(500),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS suppliers (
    id VARCHAR(36) PRIMARY KEY,
    supplier_code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    contact_person VARCHAR(150),
    email VARCHAR(150),
    phone VARCHAR(50),
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    gst_number VARCHAR(50),
    materials_supplied VARCHAR(255),
    payment_terms VARCHAR(100),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
    id VARCHAR(36) PRIMARY KEY,
    customer_code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    customer_type VARCHAR(100),
    contact_person VARCHAR(150),
    email VARCHAR(150),
    phone VARCHAR(50),
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    gst_number VARCHAR(50),
    credit_limit DOUBLE PRECISION DEFAULT 0.0,
    payment_terms VARCHAR(100),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS warehouses (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    plant_id VARCHAR(36) REFERENCES plants(id) ON DELETE SET NULL,
    location VARCHAR(200) NOT NULL,
    warehouse_type VARCHAR(100) NOT NULL,
    capacity_sqft INTEGER DEFAULT 5000,
    manager_name VARCHAR(100),
    contact_phone VARCHAR(50),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS fabrics (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    fabric_type VARCHAR(100) NOT NULL,
    composition VARCHAR(150) NOT NULL,
    gsm INTEGER,
    width_inches DOUBLE PRECISION,
    uom_id VARCHAR(36) REFERENCES uom(id) ON DELETE SET NULL,
    colour_id VARCHAR(36) REFERENCES colours(id) ON DELETE SET NULL,
    supplier_id VARCHAR(36) REFERENCES suppliers(id) ON DELETE SET NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    image_url VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS yarns (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    yarn_type VARCHAR(100) NOT NULL,
    count VARCHAR(50) NOT NULL,
    composition VARCHAR(150) NOT NULL,
    colour_id VARCHAR(36) REFERENCES colours(id) ON DELETE SET NULL,
    uom_id VARCHAR(36) REFERENCES uom(id) ON DELETE SET NULL,
    supplier_id VARCHAR(36) REFERENCES suppliers(id) ON DELETE SET NULL,
    stock_status VARCHAR(30) DEFAULT 'IN_STOCK' NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id VARCHAR(36) PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    product_type VARCHAR(100),
    fabric_id VARCHAR(36) REFERENCES fabrics(id) ON DELETE SET NULL,
    design_id VARCHAR(36) REFERENCES designs(id) ON DELETE SET NULL,
    colour_id VARCHAR(36) REFERENCES colours(id) ON DELETE SET NULL,
    size VARCHAR(50),
    uom_id VARCHAR(36) REFERENCES uom(id) ON DELETE SET NULL,
    cost_price DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
    selling_price DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
    description TEXT,
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    image_url VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS artisans (
    id VARCHAR(36) PRIMARY KEY,
    artisan_code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    phone VARCHAR(50),
    location VARCHAR(150) NOT NULL,
    skill_level VARCHAR(50) DEFAULT 'MASTER_WEAVER' NOT NULL,
    specialization VARCHAR(150) NOT NULL,
    experience_years INTEGER DEFAULT 5 NOT NULL,
    department_id VARCHAR(36) REFERENCES departments(id) ON DELETE SET NULL,
    joining_date VARCHAR(50),
    status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    profile_image_url VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS looms (
    id VARCHAR(36) PRIMARY KEY,
    loom_number VARCHAR(50) UNIQUE NOT NULL,
    loom_type VARCHAR(100) NOT NULL,
    plant_id VARCHAR(36) REFERENCES plants(id) ON DELETE SET NULL,
    location VARCHAR(150),
    capacity_meters_per_day DOUBLE PRECISION DEFAULT 5.0 NOT NULL,
    width_inches DOUBLE PRECISION DEFAULT 48.0 NOT NULL,
    assigned_artisan_id VARCHAR(36) REFERENCES artisans(id) ON DELETE SET NULL,
    installation_date VARCHAR(50),
    last_maintenance_date VARCHAR(50),
    status VARCHAR(20) DEFAULT 'RUNNING' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Operational Tables
CREATE TABLE IF NOT EXISTS production_orders (
    id VARCHAR(36) PRIMARY KEY,
    order_number VARCHAR(50) UNIQUE NOT NULL,
    product_id VARCHAR(36) REFERENCES products(id) ON DELETE SET NULL,
    loom_id VARCHAR(36) REFERENCES looms(id) ON DELETE SET NULL,
    artisan_id VARCHAR(36) REFERENCES artisans(id) ON DELETE SET NULL,
    target_quantity INTEGER NOT NULL,
    completed_quantity INTEGER DEFAULT 0 NOT NULL,
    start_date VARCHAR(50),
    target_end_date VARCHAR(50),
    status VARCHAR(30) DEFAULT 'IN_PROGRESS' NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_items (
    id VARCHAR(36) PRIMARY KEY,
    item_code VARCHAR(50) UNIQUE NOT NULL,
    item_name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    warehouse_id VARCHAR(36) REFERENCES warehouses(id) ON DELETE SET NULL,
    quantity_on_hand DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
    min_reorder_level DOUBLE PRECISION DEFAULT 10.0 NOT NULL,
    unit_of_measure VARCHAR(20) DEFAULT 'Meters' NOT NULL,
    batch_number VARCHAR(50),
    status VARCHAR(20) DEFAULT 'AVAILABLE' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id VARCHAR(36) PRIMARY KEY,
    po_number VARCHAR(50) UNIQUE NOT NULL,
    supplier_id VARCHAR(36) REFERENCES suppliers(id) ON DELETE SET NULL,
    total_amount DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
    order_date VARCHAR(50) NOT NULL,
    expected_delivery_date VARCHAR(50),
    status VARCHAR(30) DEFAULT 'PENDING_RECEIPT' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_orders (
    id VARCHAR(36) PRIMARY KEY,
    so_number VARCHAR(50) UNIQUE NOT NULL,
    customer_id VARCHAR(36) REFERENCES customers(id) ON DELETE SET NULL,
    total_amount DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
    order_date VARCHAR(50) NOT NULL,
    dispatch_date VARCHAR(50),
    status VARCHAR(30) DEFAULT 'PROCESSING' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS quality_inspections (
    id VARCHAR(36) PRIMARY KEY,
    inspection_number VARCHAR(50) UNIQUE NOT NULL,
    product_id VARCHAR(36) REFERENCES products(id) ON DELETE SET NULL,
    inspector_name VARCHAR(100) NOT NULL,
    fabric_grade VARCHAR(20) DEFAULT 'A_GRADE' NOT NULL,
    defects_found TEXT,
    inspection_date VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'PASSED' NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
